version: '3.5'
services:
  ssdlcproto:
    build:
      context: app/
      dockerfile: Dockerfile
      network: host
    container_name: ssdlc-proto
    ports:
    - 8000:8000
#    command: python main.py
#    depends_on:
#      - seed
##      - postgres

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8081:8080