"""initial

Revision ID: 748538322500
Revises: 316aaedb8536
Create Date: 2023-03-16 21:20:06.659852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748538322500'
down_revision = '316aaedb8536'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
