"""Initial

Revision ID: cf4fa3651f5c
Revises: 9a3a7d6645ef
Create Date: 2023-03-10 06:45:04.293661

"""

# revision identifiers, used by Alembic.
revision = 'cf4fa3651f5c'
down_revision = '9a3a7d6645ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
