default:
  query: "Dependency Injector"
  limit: 10
storages:
  database: "postgresql+asyncpg://postgres:postgres@192.168.1.7:5432/ssdlc02"
auth:
  jwt_secret_key: "KEY"
  jwt_algorithm: "HS256"
  access_token_expire_in_min: 30